from .assembling_kits import AssemblingKitsEnv
from .lift_peg_upright import LiftPegUprightEnv
from .peg_insertion_side import PegInsertionSideEnv
from .pick_clutter_ycb import PickClutterYCBEnv
from .pick_cube import PickCubeEnv
from .pick_single_ycb import PickSingleYCBEnv
from .plug_charger import PlugChargerEnv
from .pull_cube import PullCubeEnv
from .push_cube import PushCubeEnv
from .stack_cube import StackCubeEnv
from .turn_faucet import TurnFaucetEnv
from .two_robot_pick_cube import TwoRobotPickCube
from .two_robot_stack_cube import TwoRobotStackCube
from .poke_cube import PokeCubeEnv
from .place_sphere import PlaceSphereEnv
from .roll_ball import RollBallEnv
from .push_t import PushTEnv
from .pull_cube_tool import PullCubeToolEnv

#  custom envs
from .push_green_to_red import PushGreenToRedEnv
from .pick_cube_green import PickCubeGreenEnv
from .rotate_cube import RotateCubeEnv
from .open_drawer import OpenDrawerEnv
from .close_drawer import CloseDrawerEnv
from .pick_banana_margin import PickBananaMarginEnv
from .pick_banana_occlusion import PickBananaOcclusionEnv
from .color_order_stack import ColorOrderStackEnv
from .pick_cube_occlusion import PickCubeOcclusionEnv